{
  "name": "webpack-demo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "webpack --config webpack.config.js",
    "tomcat": "startup.bat",
    "shutdownserver": "shutdown.bat"
  },
  "keywords": [],
  "author": "LLJ",
  "license": "ISC",
  "devDependencies": {
    "@babel/cli": "^7.8.3",
    "@babel/plugin-transform-runtime": "^7.7.6",
    "@typescript-eslint/eslint-plugin": "^2.17.0",
    "@typescript-eslint/parser": "^2.17.0",
    "autoprefixer": "^9.7.4",
    "copy-webpack-plugin": "^5.1.1",
    "css-loader": "^3.4.0",
    "eslint": "^6.8.0",
    "eslint-loader": "^3.0.3",
    "eslint-plugin-vue": "^6.1.2",
    "file-loader": "^5.0.2",
    "html-loader": "^0.5.5",
    "html-webpack-plugin": "^3.2.0",
    "inline-manifest-webpack-plugin": "^4.0.2",
    "jquery": "^3.4.1",
    "less": "^3.10.3",
    "less-loader": "^5.0.0",
    "mini-css-extract-plugin": "^0.9.0",
    "node-sass": "^4.13.1",
    "postcss-loader": "^3.0.0",
    "rimraf": "^3.0.0",
    "sass-loader": "^8.0.2",
    "style-loader": "^1.1.2",
    "terser-webpack-plugin": "^2.3.2",
    "url-loader": "^3.0.0",
    "vue-loader": "^15.8.3",
    "vue-style-loader": "^4.1.2",
    "vue-template-compiler": "^2.6.11",
    "webpack": "^4.41.5",
    "webpack-cli": "^3.3.10"
  },
  "dependencies": {
    "@babel/core": "^7.7.7",
    "@babel/preset-env": "^7.7.7",
    "@babel/runtime": "^7.7.7",
    "babel-loader": "^8.0.0-beta.0",
    "dotenv": "^8.2.0",
    "ejs": "^3.0.1",
    "ejs-loader": "^0.3.5",
    "expose-loader": "^0.7.5",
    "vue": "^2.6.11",
    "vue-router": "^3.1.3",
    "vuex": "^3.1.2"
  }
}
